practice-for-ch-rails-music-app-long-practice-main/MusicApp/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resource :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show]

end

practice-for-ch-rails-music-app-long-practice-main/MusicApp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

practice-for-ch-rails-music-app-long-practice-main/MusicApp/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint           not null, primary key
#  email           :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
class User < ApplicationRecord
    validates :email, :password_digest, :session_token, uniqueness: true 
    validates :password, length: {minimum: 6}, allow_nil: true
    after_initialize :ensure_session_token
    attr_reader :password

    def self.find_by_credentials(email, password)
        user = User.find_by(email: email)
        if user && user.is_password?(password)
            return user
        else
            return nil 
        end
    end

    def password=(password)
        @password = password
        self.password_digest = BCrypt::Password.create(password)
    end

    def is_password?(password)
        BCrypt::Password.new(self.password_digest).is_password?(password)
    end

    def reset_session_token!
        self.session_token = generate_session_token
        self.save!
        self.session_token
    end

    private

    def generate_session_token
        loop do
            session_token = SecureRandom::urlsafe_base64(16)
            return session_token unless User.exists?(session_token: session_token)
        end
    end

    def ensure_session_token
        if !self.session_token
            self.session_token = generate_session_token
        end
    end


    
end

practice-for-ch-rails-music-app-long-practice-main/MusicApp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user, :logged_in?
    skip_before_action :verify_authenticity_token

    def login!(user)
        user.reset_session_token!
        session[:session_token] = user.session_token
    end

    def current_user
        User.find_by(session_token: session[:session_token])
    end

    def logged_in?
        !!current_user
    end

    def require_logged_out
        redirect_to users_url if logged_in?
    end
end

practice-for-ch-rails-music-app-long-practice-main/MusicApp/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
        # debugger
        @user = User.new
        render :new 
    end

    def create
        @user = User.find_by_credentials(params[:user][:email], params[:user][:password])
        if @user 
            login!(@user)
            redirect_to user_url
        else
            @user = User.new(email: params[:user][:email])
            render :new 
        end
    end

    def destroy
        @user = current_user 
        if @user
            current_user.reset_session_token!
            session[:session_token] = nil 
        end
        redirect_to new_session_url
    end
end

practice-for-ch-rails-music-app-long-practice-main/MusicApp/app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
        render :new 
    end

    def create
        @user = User.new(user_params)
        if @user.save 
            session[:session_token] = @user.session_token
            redirect_to new_user_url 
        else 
            render :new 
        end
    end

    private
    def user_params
        params.require(:user).permit(:email, :password)
    end
end

practice-for-ch-rails-music-app-long-practice-main/MusicApp/app/helpers/application_helper.rb
module ApplicationHelper
end

practice-for-ch-rails-music-app-long-practice-main/MusicApp/app/helpers/sessions_helper.rb
module SessionsHelper
end

practice-for-ch-rails-music-app-long-practice-main/MusicApp/app/helpers/users_helper.rb
module UsersHelper
end

practice-for-ch-rails-music-app-long-practice-main/MusicApp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "reset" %>
    <%= stylesheet_link_tag "application" %>
  </head>
  <header>
  <%if logged_in?%>
  <h2><%=current_user.email%></h2>
  <form action=<%=sessions_url%> method="POST">
  <input type="hidden" name="_method" value="DELETE">
  <input type="submit" value="Log Out">
  </form>
  <%else%>
  <a href=<%=new_sessions_url%>>Log In</a>
  <a href=<%=new_user_url%>>Sign Up</a>
  <%end%>
</header>
  <body>
    <%= yield %>
  </body>
</html>

practice-for-ch-rails-music-app-long-practice-main/MusicApp/app/views/users/new.html.erb
<label for="email">Email</label>
<input type="text" id="email" name="user[email]" value="<%=@user.email%>">
<br>
<label for="password">Password</label>
<input type="password" id="password" name="user[password]">
<br>
<input type="submit" value="Create User">